### ISSUE TITLE
how to ignore vendor files ?

### ISSUE THREAD

**Issue by mathilde-pellerin** [brunch/jshint-brunch#20]
Hi,

I have a problem to use jshint-brunch on a project in which I have a vendor folder : jshint parse vendor folder and so compilation fails.
I use .jshintrc file to configure jshint.

If I set path watched like this (instead of let default path configuration) :
```
paths: {
	"watched": ['app']
},
```
jshint don't parse vendor folder but brunch neither, so my vendor files are not compiled.

Is there a way that I miss to configure jshint-brunch to ignore my vendor folder?

**Comment by paulmillr** [comment]
As you can see in the README, you can configure patterns in this way:

```
# brunch-config.coffee
exports.config =
  plugins:
    jshint:
      pattern: /^app\/.*\.js$/
```
